device: ''

#deepsort
config_deepsort: ../../settings/deep_sort.yaml
deep_sort_weights: ../../models/ckpt.t7

#yolo
yolo_weights: ../../models/yolov5s.pt
agnostic_nms: false
augment: false
classes: [1, 2, 3, 5, 7]
conf_thres: 0.35
imgsz:
- 640
iou_thres: 0.5
max_det: 1000
dnn: false
evaluate: false
half: false
visualize: false

#in-out
fourcc: mp4v
source: ../../videos/cut3.avi
output: inference/output
save_csv: false
save_txt: false
save_vid: true
show_vid: false

#lines zones
upper_ratio: 0.4
lower_ratio: 0.9231

#DB
upload_db: false

#deep_sort_pytorch/configs/deep_sort.yaml
#../settings/deep_sort.yaml
#../../video_nhax_cut_resize2.mp4
#deep_sort_weights: deep_sort_pytorch/deep_sort/deep/checkpoint/ckpt.t7